---
title: "Plot 1"
format: html
---

```{r}
devtools::load_all()
library(tidyverse)
library(metill)
library(ggtext)
theme_set(theme_metill())
```


```{r}
d <- points |> 
    filter(round == "final", year >= 2000) |> 
    count(from, to, wt = points, name = "points") |> 
    mutate(
        p = points / sum(points),
        .by = to
    ) 
```


```{r}
plot_dat <- d |> 
    filter(
        (to == "Iceland")
    ) |> 
    select(
        country = from, to_iceland = points
    ) |> 
    inner_join(
        d |> 
            filter(
                (from == "Iceland")
            ) |> 
            select(
                country = to, from_iceland = points
            ),
        by = join_by(country)
    )  |> 
    inner_join(
        country_names(),
        by = join_by(country)
    ) |> 
    mutate(
        diff = from_iceland - to_iceland,
        land = fct_reorder(land, -diff)
    )
```

```{r}
max_val <- max(c(plot_dat$to_iceland, plot_dat$from_iceland))
min_val <- min(c(plot_dat$to_iceland, plot_dat$from_iceland))



p <- plot_dat |> 
    ggplot(aes(diff, land)) +
    geom_vline(
        xintercept = 0,
        lty = 2,
        alpha = 0.5,
        linewidth = 0.4
    ) +
    geom_segment(
        aes(xend = 0, yend = land),
        alpha = 0.5,
        linewidth = 0.3
    ) +
    geom_point(
        size = 2.5
    ) +
    geom_richtext(
        data = tibble(x = 1),
        inherit.aes = FALSE,
        x = -24,
        y = -1.4,
        label.colour = NA,
        fill = NA,
        label = "&larr; Við **fáum** fleiri stig",
        hjust = 0,
        size = 4,
        colour = "grey40"
    ) +
    geom_richtext(
        data = tibble(x = 1),
        inherit.aes = FALSE,
        x = 32, 
        y = -1.4, 
        label.colour = NA,
        fill = NA,
        label = "Við **gefum** fleiri stig &rarr;", 
        hjust = 1,
        size = 4,
        colour = "grey40"
    ) +
    annotate(
        geom = "richtext",
        x = 1.5,
        y = 25,
        label = str_c(
            "Lönd nálægt línunni<br>gefa okkur jafnmörg stig<br>og við gefum þeim"
        ),
        label.colour = NA,
        fill = NA,
        hjust = 0,
        family = "Lato",
        color = "grey40"
    ) +
    annotate(
        geom = "curve",
        x = 9.1, xend = 0.5,
        y = 26.5, yend = 31,
        curvature = 0.7,
        angle = 100,
        linewidth = 0.4,
        arrow = arrow(length = unit(7, "point"), type = "closed"),
        color = "grey40"
    ) +
    scale_x_tufte(
        breaks = tufte_breaks(plot_dat$diff)
    ) +
    coord_cartesian(
        clip = "off"
    ) +
    theme(
        legend.position = "none",
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 10)),
        plot.margin = margin(t = 5, r = 15, b = 5, l = 5)
    ) +
    labs(
        x = NULL,
        y = NULL,
        title = "Gefum við jafnmörg stig og við fáum?",
        subtitle = "Munur á **fengnum** og **gefnum** stigum á úrslitakeppnum árin 2000 til 2019",
        caption = "\n\nGögn: https://github.com/Spijkervet/eurovision-dataset"
    )


ggsave(
    plot = p,
    filename = "points_comp.png",
    width = 8, height = 8, scale = 1
)
```

